
project_id = "qrpppkxwvmngepzznorf"
[functions.generate-interview-questions]
verify_jwt = false
[functions.generate-answer]
verify_jwt = false
[functions.guided-response-generator]
verify_jwt = false

# Site configuration
site_url = "https://storyline.tryhireme.com"
additional_redirect_urls = ["https://storyline.tryhireme.com/*"]
