
project_id = "qrpppkxwvmngepzznorf"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

[[functions]]
name = "storyline-audio-function"
verify_jwt = true

[[functions]]
name = "storyline-create-behavioral-interview"
verify_jwt = true

[[functions]]
name = "storyline-guided-response-generator"
verify_jwt = true

[[functions]]
name = "storyline-question-vault-prep"
verify_jwt = true

[[functions]]
name = "storyline-firecrawl-scraper"
verify_jwt = true

[[functions]]
name = "stripe-subscription-manager"
verify_jwt = true
