// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sybuuvdthgjpcrbiwphi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN5YnV1dmR0aGdqcGNyYml3cGhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUzNzAwMjQsImV4cCI6MjA3MDk0NjAyNH0.he7bTscNChfnUOTDnrFligo4hE4pQclNq1gOPqJ9POU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});